default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["TACOGRAM_FINAL_DATABASE_USERNAME"] %>
  password: <%= ENV["TACOGRAM_FINAL_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: db/development.sqlite3  # SQLite for development

test:
  <<: *default
  database: db/test.sqlite3  # SQLite for test

production:
  <<: *default
  database: tacogram_final_production
  username: annamerrymanlee  # Replace with your database username for production
  password: <%= ENV["TACOGRAM_FINAL_DATABASE_PASSWORD"] %>  # Use the production password from environment variables
  host: <%= ENV["DATABASE_HOST"] %>  # Optional, set this if your database is hosted somewhere else
  port: 5432  # Default PostgreSQL port
