default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["TACOGRAM_FINAL_DATABASE_USERNAME"] %>
  password: <%= ENV["TACOGRAM_FINAL_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: db/development.sqlite3  # SQLite for development

test:
  <<: *default
  database: db/test.sqlite3  # SQLite for test

production:
  <<: *default
  adapter: postgresql
  database: tacogram_final_production
  username: tacogram_final
  password: <%= ENV["TACOGRAM_FINAL_DATABASE_PASSWORD"] %>
